In [4]:
import pandas as pd
import numpy as np
import matplotlib as pyplot

In [5]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [9]:
dep=dataset['classification_yes']
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[-0.67992978,  0.26534721,  0.13647691, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.30730707,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168,  1.80469462,  2.56692738, ...,  0.50671171,
        -0.51229234,  2.28035085],
       ...,
       [-0.43312057,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-1.35865512,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-0.06290675, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [12]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid = {'kernel':['rbf','poly','sigmond','linear'], 
              'C':[10,100,100,1000,2000,3000], 'gamma':['auto','scale']}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True, verbose=3,n_jobs=-1,scoring='f1_weighted')
#fitting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

C:\Users\bhava\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
60 fits failed out of a total of 240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\bhava\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\bhava\Anaconda3\lib\site-packages\sklearn\svm\_base.py", line 255, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "C:\Users\bhava\Anaconda3\lib\site-packages\sklearn\svm\_base.py", line 333, in _dense_fit
    random_seed=random_seed,
  File "sklearn\svm\_libsvm.pyx", line 173, in sklearn.svm._libsvm.fit
ValueError: 'sigmond' is not in list

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\bhava\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.99285439 0.98923593        nan 0.98212161 0.99285439 0.98923593
        nan 0.98212161 0.98926456 0.98570339        nan 0.98212161
 0.98926456 0.98570339        nan 0.98212161 0.98926456 0.98570339
        nan 0.98212161 0.98926456 0.98570339        nan 0.98212161
 0.98926456 0.98215036        nan 0.98212161 0.98926456 0.98215036
        nan 0.98212161 0.98926456 0.98215036        nan 0.98212161
 0.98926456 0.98215036        nan 0.98212161 0.98926456 0.98215036
        nan 0.98212161 0.98926456 0.98215036        nan 0.98212161]
  category=UserWarning,

GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmond', 'linear']},
             scoring='f1_weighted', verbose=3)

In [15]:
#print best paramter after tuning
#print(grid.best_params_)
re=grid.cv_results_
grid_predcitions = grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predcitions)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predcitions)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predcitions,average='weighted')
print("The R_score value for the best parameter{}:".format(grid.best_params_),f1_score)

The R_score value for the best parameter{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}: <function f1_score at 0x000001B07B01B1F8>

In [17]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[45  0]
 [ 2 73]]

In [18]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9994074074074074

In [20]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009200,0.001167,0.002801,0.000400,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,1.000000,1.000000,0.992854,0.008752,1
1,0.017805,0.001169,0.003004,0.000003,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,1.000000,0.964286,1.000000,0.981894,0.989236,0.014311,13
2,0.001800,0.000401,0.000000,0.000000,10,auto,sigmond,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,37
3,0.006169,0.000468,0.002468,0.000486,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
4,0.007576,0.000474,0.002620,0.000454,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,1.000000,1.000000,0.992854,0.008752,1
5,0.016221,0.001214,0.002733,0.000343,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,1.000000,0.964286,1.000000,0.981894,0.989236,0.014311,13
6,0.002177,0.000253,0.000000,0.000000,10,scale,sigmond,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
7,0.005776,0.000310,0.002426,0.000339,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
8,0.006788,0.000800,0.002605,0.000374,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
9,0.013438,0.001979,0.001994,0.000755,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,15
10,0.001464,0.000507,0.000000,0.000000,100,auto,sigmond,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,40
11,0.004745,0.000597,0.002049,0.000639,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
12,0.005827,0.001038,0.002236,0.000396,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
13,0.013569,0.001079,0.002183,0.000512,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,15
14,0.001379,0.000509,0.000000,0.000000,100,scale,sigmond,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,47
15,0.006170,0.000743,0.002002,0.000633,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
16,0.006202,0.001327,0.002204,0.000407,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
17,0.012714,0.001353,0.002849,0.000702,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,15
18,0.001648,0.000438,0.000000,0.000000,100,auto,sigmond,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,42
19,0.005800,0.001165,0.001801,0.000400,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
20,0.006172,0.000630,0.002407,0.000498,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
21,0.012762,0.001016,0.002211,0.000398,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,15
22,0.001627,0.000508,0.000000,0.000000,100,scale,sigmond,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
23,0.005645,0.000793,0.002327,0.000677,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
24,0.006517,0.001041,0.002402,0.000489,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
25,0.013510,0.002039,0.002771,0.000598,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
26,0.001304,0.000392,0.000000,0.000000,1000,auto,sigmond,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,41
27,0.005274,0.001479,0.001802,0.000749,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
28,0.006864,0.001009,0.002316,0.000409,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
29,0.014084,0.000559,0.002611,0.000463,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
30,0.001651,0.000532,0.000000,0.000000,1000,scale,sigmond,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,46
31,0.006096,0.000761,0.002127,0.000185,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
32,0.006607,0.000909,0.002550,0.000395,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
33,0.013909,0.001951,0.002085,0.000164,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
34,0.001855,0.000523,0.000000,0.000000,2000,auto,sigmond,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
35,0.006848,0.001231,0.002061,0.000116,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
36,0.007204,0.000450,0.002004,0.000006,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
37,0.013750,0.001431,0.002182,0.000744,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
38,0.001433,0.000532,0.000000,0.000000,2000,scale,sigmond,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,48
39,0.005441,0.001006,0.002562,0.000494,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
40,0.007204,0.001002,0.002242,0.000387,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
41,0.011848,0.002738,0.002261,0.000383,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
42,0.001266,0.000380,0.000000,0.000000,3000,auto,sigmond,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmond'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,39
43,0.006063,0.000969,0.001927,0.000198,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
44,0.005362,0.000859,0.002120,0.000157,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,3
45,0.010973,0.002362,0.002211,0.000395,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,19
46,0.001813,0.000408,0.000000,0.000000,3000,scale,sigmond,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
47,0.004092,0.000659,0.001288,0.000389,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25

In [23]:
age_input=float(input("Age:"))
bp_input=float(input("BP:"))
al_input=float(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SU:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pcv_input=float(input("PCV:"))
wc_input=float(input("WC:"))
rc_input=float(input("RC:"))
sg_b_input=float(input("SG_B:"))
sg_c_input=float(input("SG_C:"))
sg_d_input=float(input("SG_D:"))
sg_e_input=float(input("SG_E:"))
rbc_normal_input=float(input("RBC_NORMAL:"))
pc_normal_input=float(input("PC_NORMAL:"))
pcc_present_input=float(input("PCC_NORMAL:"))
ba_present_input=float(input("BA_PRESENT:"))
htn_yes_input=float(input("HTN_YES:"))
dm_yes_input=float(input("DM_YES:"))
cad_yes_input=float(input("CAD_YES:"))
appet_yes_input=float(input("APPET_YES:"))
pe_yes_input=float(input("PE_YES:"))
ane_yes_input=float(input("ANE_YES:"))

Age:2
BP:76.4599483204134
AL:3
SU:0
BGR:148.112676056338
BU:57.4821052631579
SU:0
SOD:137.52875399361
POT:4.62724358974359
HRMO:12.5181556195965
PCV:38.8689024390243
WC:8408.19112627986
RC:4.70559701492537
SG_B:1
SG_C:1
SG_D:0
SG_E:0
RBC_NORMAL:1
PC_NORMAL:1
PCC_NORMAL:1
BA_PRESENT:1
HTN_YES:0
DM_YES:0
CAD_YES:0
APPET_YES:1
PE_YES:0
ANE_YES:1

In [24]:
Future_Prediction=grid.predict([[age_input, bp_input, al_input, su_input, bgr_input, bu_input, sc_input, sod_input, pot_input, 
hrmo_input, pcv_input, wc_input, rc_input, sg_b_input, sg_c_input, sg_d_input, sg_e_input, 
rbc_normal_input, pc_normal_input, pcc_present_input, ba_present_input, htn_yes_input, dm_yes_input, cad_yes_input, appet_yes_input, pe_yes_input, ane_yes_input]])
print("Future_Prediction{}".format(Future_Prediction))

Future_Prediction[1]